### ISSUE TITLE
[BUG] Model attributes of type Object are not saved at all

### ISSUE THREAD

**Issue by MickL** [dynamoose/dynamoose#892] opened 2020-05-11 13:15 UTC
### Summary:
```ts
        const Cat = dynamoose.model('Cat', {
            name:      String,
            something: Object,
        });
  

        const attributes = {
            name: 'Meowth',
            something: {
                hello: 'world',
            }
        };
        await Cat.create(attributes);

        // Another issue: `attributes.something` is now `{}`
```

Results in:

```
aws:dynamodb:putItem:request - {
    "Item": {
        "name": {
            "S": "Meowth"
        },
        "something": {
            "M": {}
        }
    },
    "TableName": "Cat",
    "ConditionExpression": "attribute_not_exists(#__hash_key)",
    "ExpressionAttributeNames": {
        "#__hash_key": "name"
    }
}
aws:dynamodb:putItem:response - {
    "Attributes": {
        "name": {
            "S": "Meowth"
        },
        "something": {
            "M": {}
        }
    }
}
```

Also a big issue: It even changes the source attributes object and make the object empty!

Branch: querySort

**Comment by fishcharlie** [comment] 2020-05-12 00:56
@MickL This is actually the expected behavior. Try defining the [`schema`](https://dynamoosejs.com/guide/Schema#schema-object--array) setting on the `Object` attribute.

Something like:

```js
const Cat = dynamoose.model('Cat', {
    name:      String,
    something: {
        type: Object,
        schema: {
            hello: String
        }
    },
});
  

const attributes = {
    name: 'Meowth',
    something: {
        hello: 'world',
    }
};
await Cat.create(attributes);
```

Alternatively you could set the [`saveUnknown`](https://dynamoosejs.com/guide/Schema#new-dynamooseschemaschema-options) Schema setting to allow for this without defining an explicit schema, tho this isn't recommended (since the point of Dynamoose is to be more strict when it comes to this stuff, but is possible).

---

> Another issue: `attributes.something` is now `{}`

Now **that** is a bug for sure... Dynamoose shouldn't mutate objects like that. That is really gross. Haven't tested this or tried to reproduce it yet, but will look into it and see what is going on.

**Comment by MickL** [comment] 2020-05-12 08:54
I see the following issues here:
- Dynamoose should not mutate any input
- The documentation says nothing about that a schema needs to be defined for an object
- If i dont define a schema for an `Object` attribute I would expect it to just save what I put in instead of making it an empty object.
- `saveUnknown` is not available for a single attribute.

**Comment by ebrearley** [comment] 2020-05-12 22:12
Could we potentially make this a setting on the attribute?

Having a strongly typed schema is highly advantageous for long term maintainability of the software we produce.

For me (and others on my team), we took delight in defining our nested schemas. We also picked up some issues with our previous implementation along the way, which just further reinforced our appreciation of knowing that we wont have unexpected data in our database.

Yeah, I appreciate that there's some work to do with upgrading from version 1, but it's certainly worth your while!

Although, in saying this, maybe somebody has a highly dynamic application where the shape of the object is only known at run time. This is where we'd need some flexibility from Dynamoose. Maybe we can do something like:

```js
const ItemWithADynamicAttribute = new Schema({
  id: {
    type: String,
    required: true,
  },
  dynamicAttribute: {
    type: Object,
    allowAnyShape: true,
  },
  dynamicAttributeArray: {
    type: Array,
    schema: [{
      type: Object,
      allowAnyShape: true,
    }],
  },
});
```

**Comment by fishcharlie** [comment] 2020-05-12 23:18
@MickL

> Dynamoose should not mutate any input

Agreed

---

@ebrearley 

> Having a strongly typed schema is highly advantageous for long term maintainability of the software we produce.

Totally agree. This is a major reason to use Dynamoose in my opinion. It's possible to make it less strict by using `saveUnknown`, but just defaulting to that, removes a huge purpose of Dynamoose.

> Could we potentially make this a setting on the attribute?

Totally for this. Maybe `saveUnknown` on the attribute? Not really a fan of the naming `allowAnyShape`. That way it remains consistent for the Schema settings and Attribute settings.

**Comment by stepri** [comment] 2020-05-20 22:16
I did some small investigation. It is returning an empty object or array because `settings.saveUnknown` can be undefined on this line and thus `!settings.saveUnknown` returns true for all keys: https://github.com/dynamoose/dynamoose/blob/556f97e397eea7d809ca9aee089d4263ec105bf0/lib/Document.ts#L277 

Not sure where and how that property is set..

**Comment by fishcharlie** [comment] 2020-05-21 01:52
@stepri Confused about what your point is. The only todo item here is to allow `saveUnknown` to be set as an attribute setting. Oh and to ensure that it doesn't mutate the input. Is this another bug you are reporting? Or?

**Comment by stepri** [comment] 2020-05-21 12:32
@fishcharlie Ah sorry for the missing context but I was trying to understand why it returns an empty object or array even when `saveUnknown` is set to true and thus mutating data.

**Comment by fishcharlie** [comment] 2020-05-21 17:44
@stepri That almost sounds like a different bug. If `saveUnknown` is true, it shouldn't modify it when saving.

The mutating input I **think** is due to us not copying the object and just modifying the input. Which we shouldn't be doing. But if it's saving an empty object or array with `saveUnknown` set to true, that sounds like a different bug to me.

**Comment by fishcharlie** [comment] 2020-11-27 02:00
Closing in favor of #1059

**Closed by fishcharlie** 2020-11-27 02:00 UTC
Labels: status:todo, type:enhancement
