### ISSUE TITLE
[QUESTION]TypeMismatch: Expected xxx to be of type object, instead found type object

### ISSUE THREAD

**Issue by sankalan** [dynamoose/dynamoose#928] opened 2020-06-02 13:53 UTC
Hey guys I am pretty new to DynamoDB and dynamoose, trying to migrate my mongoose code/db to dynamoose/dynamodb.
I am having this exception while trying to save custom object-  "TypeMismatch: Expected name to be of type object, instead found type object".
Here is my sample code on nodejs/typescript-

```import dynamoose from "dynamoose";
  export = {
    run: async() => {
        dynamoose.aws.sdk.config.update({ 
            "accessKeyId": "AKID", 
            "secretAccessKey": "SECRET", 
            "region": "us-east-1" 
        }); 
        dynamoose.aws.ddb.local();
        const Man = dynamoose.model('Man', {
            id: String,
            name: {
                type: Object,
                schema: {
                    firstname: String,
                    lastname: String
                }
            }});
        Man.create({
            id:"random",
            name: new Name("John", "Martin")
        });
    }
}.run();
class Name {
    firstname: string;
    lastname: string;
    constructor(firstname: string, lastname: string){
        this.firstname = firstname;
        this.lastname = lastname;
    }
}
```

Can you help me with this?

**Comment by fishcharlie** [comment] 2020-06-20 18:02
@sankalan So the solution here is to change it to the following.

```js
Man.create({
    id:"random",
    name: {...new Name("John", "Martin")}
});
```

I think that this maybe needs more discussion about if we should do this automatically as part of Dynamoose. Not sure what possible side-effects there would be here.

**Comment by yashutanna** [comment] 2020-08-18 07:38
Hey @fishcharlie  I actually have the same issue but under a different schema type:

```
const Shop = new dynamoose.Schema({
    operatingHours: {
        type: Array,
        schema: [{
          type: Object,
          schema: {
            open: Boolean,
            timeFrom: Number,
            timeTo: Number,
            dayOfWeek: String
          }
        }]
      },
    })
```

with documentation example from [here](https://dynamoosejs.com/guide/Schema/#schema-object--array)

this is the error I get for reference: 

```
{
      "message": "Expected operatingHours.0 to be of type object, instead found type object.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "addBusiness"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "name": "TypeMismatch",
          "message": "Expected operatingHours.0 to be of type object, instead found type object.",
          "stacktrace": [
            "TypeMismatch: Expected operatingHours.0 to be of type object, instead found type object.",
            "    at checkTypeFunction (/Users/yashutanna/projects/restaurant-server/node_modules/dynamoose/lib/Document.ts:302:11)",
            "    at /Users/yashutanna/projects/restaurant-server/node_modules/dynamoose/lib/Document.ts:309:7",
            "    at Array.forEach (<anonymous>)",
            "    at checkTypeFunction (/Users/yashutanna/projects/restaurant-server/node_modules/dynamoose/lib/Document.ts:307:11)",
            "    at Array.map (<anonymous>)",
            "    at Function.<anonymous> (/Users/yashutanna/projects/restaurant-server/node_modules/dynamoose/lib/Document.ts:321:111)",
            "    at Generator.next (<anonymous>)",
            "    at fulfilled (/Users/yashutanna/projects/restaurant-server/node_modules/dynamoose/dist/Document.js:5:58)",
            "    at processTicksAndRejections (internal/process/task_queues.js:94:5)"
          ]
        }
      }
```

I suspect the issue is at this path `dynamoose/dist/utils/dynamoose/getValueTypeCheckResult.js` but i am struggling to figure out the logic in that file. 

I would love a workaround if this is a bigger issue?

Thanks for the awesome library!

**Comment by yashutanna** [comment] 2020-08-18 07:42
another thing to note is also the following typescript error that pops up when defining an array of objects 

```
var Boolean: BooleanConstructor
Type '{ type: ObjectConstructor; schema: { open: BooleanConstructor; timeFrom: NumberConstructor; timeTo: NumberConstructor; dayOfWeek: StringConstructor; }; }[]' is not assignable to type 'SchemaDefinition | SchemaDefinition[] | undefined'.
  Type '{ type: ObjectConstructor; schema: { open: BooleanConstructor; timeFrom: NumberConstructor; timeTo: NumberConstructor; dayOfWeek: StringConstructor; }; }[]' is not assignable to type 'SchemaDefinition[]'.
    Type '{ type: ObjectConstructor; schema: { open: BooleanConstructor; timeFrom: NumberConstructor; timeTo: NumberConstructor; dayOfWeek: StringConstructor; }; }' is not assignable to type 'SchemaDefinition'.
      Property 'schema' is incompatible with index signature.
        Type '{ open: BooleanConstructor; timeFrom: NumberConstructor; timeTo: NumberConstructor; dayOfWeek: StringConstructor; }' is not assignable to type 'string | StringConstructor | BooleanConstructor | NumberConstructor | typeof Buffer | DateConstructor | ObjectConstructor | ArrayConstructor | AttributeDefinition'.
          Object literal may only specify known properties, and 'open' does not exist in type 'StringConstructor | BooleanConstructor | NumberConstructor | typeof Buffer | DateConstructor | ObjectConstructor | ArrayConstructor | AttributeDefinition'.ts(2322)
```

**Comment by yashutanna** [comment] 2020-08-18 09:43
the typescript issue was as a result of me still using the 2.3.0-beta_1 package. The type error has been resolved in v2.3.0

**Comment by sofyan-ahmad** [comment] 2020-12-20 10:29
I'm having a similar issue on v 2.5.0. Here is my schema
```
export const BundleDetailSchema = new Schema({
  productSku: {
    type: String,
  },
  qty: {
    type: Number,
  },
});

export const BundleSchema = new Schema({
  id: {
    type: String,
    hashKey: true,
    default: uuid(),
  },
  name: {
    type: String,
    rangeKey: true,
  },
  bundles: {
    type: Array,
    schema: [BundleDetailSchema],
  },
  price: Number,
  type: String,
});
```

I found the workaround. I just need to convert the javascript object class into a plain object before inserting the `BundleDetailSchema` data into create arguments:

```
   const bundles: BundleDetail[] = [];

    createBundleInput.bundles.map((bundle) => {
      // convert from class object into plain object
      bundles.push({ productSku: bundle.productSku, qty: bundle.qty });
    });

    createBundleInput.bundles = bundles;

    return this.bundleModel.create(createBundleInput);
```

**Closed** 2020-12-23 21:34 UTC
Labels: type:question

**Comment by RITISHKARKIUNH** [comment] 2020-12-31 05:13
Hello i am having same issue with version 2.5.0 i am trying to save shopify product object using dynamoose
I am getting error in string and it is identifying it as an object 
TypeMismatch: Expected propertyX to be of type string, instead found type object.

This is my schema and i am getting error for key "featuredImage"
`
const shopifyProduct = {
    "cursor": String,
    "bodyHtml": {
        type: String,
        default: '',
    },
    "createdAt": String,
    "description": {
        type: String,
        default: '',
    },
    "descriptionHtml": {
        type: String,
        default: '',
    },
    "descriptionPlainSummary": {
        type: String,
        default: '',
    },
    "featuredImage": {
        type: Object,
        schema: {
            "id": String,
            "src": String,
            "altText": String,
        },
        default: null,
    },
    "id": String,
    "images": {
        type: Array,
        schema: [{
            type: Object,
            schema: {
                "id": String,
                "src": String,
                "altText": String,
            },
        }],
        default: [],
    },
    "title": {
        type: String,
        default: '',
    },
    "totalVariants": Number,
    "variants": {
        type: Array,
        schema: [{
            type: Object,
            schema: shopifyProductVariant,
        }],
        default: [],
    },
    "priceRange": {
        type: Object,
        schema: shopifyProductPriceRange,
    },
    "productType": {
        type: String,
        default: '',
    },
    "publishedAt": String,
    "tags": {
        type: Array,
        schema: [String],
        default: [],
    }
}`

And this is the error i get 
`
TypeMismatch: Expected products.0.featuredImage.altText to be of type string, instead found type object.
    at checkTypeFunction (/Users/ritishkarki/Desktop/projects/Impct/impct-int-shopify-app/node_modules/dynamoose/lib/Document.ts:326:11)
    at Array.map (<anonymous>)
    at Function.Document.objectFromSchema (/Users/ritishkarki/Desktop/projects/Impct/impct-int-shopify-app/node_modules/dynamoose/lib/Document.ts:347:111)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at Document.toDynamo (/Users/ritishkarki/Desktop/projects/Impct/impct-int-shopify-app/node_modules/dynamoose/lib/Document.ts:505:17)
    at async Promise.all (index 0)
    at /Users/ritishkarki/Desktop/projects/Impct/impct-int-shopify-app/node_modules/dynamoose/lib/Document.ts:189:5
    at Function.<anonymous> (/Users/ritishkarki/Desktop/projects/Impct/impct-int-shopify-app/services/impct-data/shopify-products-model.js:14:27)
    at saveProducts (/Users/ritishkarki/Desktop/projects/Impct/impct-int-shopify-app/services/product.js:160:30) Problem saving shopify products to dynamo

TypeMismatch: Expected products.0.featuredImage.altText to be of type string, instead found type object.
    at checkTypeFunction (/Users/ritishkarki/Desktop/projects/Impct/impct-int-shopify-app/node_modules/dynamoose/lib/Document.ts:326:11)
    at Array.map (<anonymous>)
    at Function.Document.objectFromSchema (/Users/ritishkarki/Desktop/projects/Impct/impct-int-shopify-app/node_modules/dynamoose/lib/Document.ts:347:111)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at Document.toDynamo (/Users/ritishkarki/Desktop/projects/Impct/impct-int-shopify-app/node_modules/dynamoose/lib/Document.ts:505:17)
    at async Promise.all (index 0)
    at /Users/ritishkarki/Desktop/projects/Impct/impct-int-shopify-app/node_modules/dynamoose/lib/Document.ts:189:5
    at Function.<anonymous> (/Users/ritishkarki/Desktop/projects/Impct/impct-int-shopify-app/services/impct-data/shopify-products-model.js:14:27)
    at saveProducts (/Users/ritishkarki/Desktop/projects/Impct/impct-int-shopify-app/services/product.js:160:30) Error saving the processed products

`

Did anyone ran into same issue ?

**Comment by fishcharlie** [comment] 2020-12-31 06:10
@RITISHKARKIUNH This is not the same issue nor does your comment have enough information to debug. The error message in your case is very clear.

**Comment by hpinheiro-godaddy** [comment] 2022-08-25 18:59
I'm facing that same error message and it happens because `(val) => Boolean(val) && val.constructor === Object` isn't enough to asserts that we have a plain object. Several libs (including express) use `Object.create(null)` to parse inputs and that kind of object will be considered invalid through `(val) => Boolean(val) && val.constructor === Object`.

`.constructor` isn't reliable for that case. Here is a more strict technic to assert an object https://github.com/jonschlinkert/is-plain-object/blob/master/is-plain-object.js.

And for my case, I have a deep object built from a GraphQL mutation, destructuring each level isn't productive and includes more loops (each `...` is a loop!). Currently, we're doing a deep copy (replacing the `prototype.constructor`) before sending the objects to Dynamoose.

I did a good enough check to improve the current validation: https://github.com/dynamoose/dynamoose/pull/1481

**Comment by thelaziestdev** [comment] 2022-12-23 09:42
> @albertoantunes This is the expected behavior. You can't store instances of classes in Dynamoose. You have to convert it to a plain JSON object.

Why is it an expected behavior @fishcharlie ?
Why to not support classes instances as well?

**Comment by fishcharlie** [comment] 2022-12-23 18:02
@thelaziestdev It's just how it was designed. Lots of factors to take into consideration related to inheritance, static properties, computed properties, and more.

Remember, a class at its core is a function. It's just syntax sugar.

If you want to come up with a proposal to address all the concerns, and want to take the lead on writing a PR, I'd be happy to help review things and give feedback. But it's fairly low priority. The users of Dynamoose today are the best ones to solve the issues I mentioned above and turn their class instances into plain objects.
