### ISSUE TITLE
TypeError: key.split is not a function

### ISSUE THREAD

**Issue by softmarshmallow** [dynamoose/dynamoose#1049] opened 2020-11-25 03:10 UTC
Schema
``` ts

export const NestedLayer = new dynamoose.Schema({
    nodeId: String,
    key: String,
    index: Number,
    name: String,
    sdkVersion: String,
    node: String,
    type: {
        "type": String,
        "enum": ["INSTANCE", "GROUP", "VANILLA"]
    },
    layers: {
        type: Array,
        required: false,
        schema: [{
            type: Object,
            schema: dynamoose.THIS as any
        }]
    },
    componentId: String,
    width: Number,
    height: Number,
}, {
    saveUnknown: true,
})

export const SceneScheam = new dynamoose.Schema({
    id: String,
    projectId: String,
    fileId: String,
    nodeId: String,
    sdkVersion: String,
    //DesignPlatformType
    designPlatform: {
        "type": String,
        "enum": ["com.figma.Desktop", "com.bohemiancoding.sketch3", "xyz.bridged.bridged"]
    },
    cachedPreview: String,
    // SceneType
    sceneType: {
        "type": String,
        "enum": ["SCREEN", "COMPONENT", "DOCS"]
    },
    route: String,
    path: String,
    name: String,
    description: String,
    tags: {
        "type": Set,
        "schema": [String]
    },
    alias: String,
    variant: String,
    layers: {
        type: Array,
        schema: [NestedLayer as any]
    },
    width: Number,
    height: Number

}, {
    saveUnknown: true
})

export const Scene = dynamoose.model(TABLE, SceneScheam);


```

```
TypeError: key.split is not a function
    at /Users/-/Documents/GitHub/services/node_modules/dynamoose/lib/utils/dynamoose/wildcard_allowed_check.ts:4:25
    at Array.find (<anonymous>)
    at Object.module.exports [as wildcard_allowed_check] (/Users/-/Documents/GitHub/services/node_modules/dynamoose/lib/utils/dynamoose/wildcard_allowed_check.ts:3:30)
    at checkTypeFunction (/Users/-/Documents/GitHub/services/node_modules/dynamoose/lib/Document.ts:329:50)
    at Array.map (<anonymous>)
    at Function.<anonymous> (/Users/-/Documents/GitHub/services/node_modules/dynamoose/lib/Document.ts:334:111)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/-/Documents/GitHub/services/node_modules/dynamoose/dist/Document.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

This error comes after i add     `saveUnknown: true`

version : 2.4.0

**Comment by fishcharlie** [comment] 2020-11-27 04:30
@softmarshmallow I know this is going to be frustrating. But I now have to close this issue. Normally for issues that don't meet our guidelines, I keep them open if they have an attached PR by the same author. But now that your PR is closed, I have to close this issue as well.

I took your code you put above, and tried to run it. And I'm getting no errors at all.

So I can't reproduce this, and therefore I can't debug or fix it.

On top of all of that, you didn't fill out the issue template.

As I said, I normally keep issues open even if they don't follow the guidelines if they have an open PR by the same author. This is because if the issue is solved via that PR, the issue template isn't as relevant anymore. The reasons for the issue template don't matter as much. Good unit tests, documentation changes (if necessary), etc. all help provide context to the issue and are almost a replacement for the issue template.

Again. I **really** want to fix this. But I'm not sure how I can if I can't reproduce it (hence why I was asking for unit tests and more information on your PR). If you have any suggestions for how to move forward, I'd happily reopen this PR. But at this point I'm at a loss. You refused to make changes to the PR and provide additional information, you didn't fill out the issue template, I can't reproduce this issue, etc. I'm not sure how to proceed now.

**Closed by fishcharlie** 2020-11-27 04:30 UTC
Labels: type:bug

**Comment by softmarshmallow** [comment] 2020-11-27 04:32
If it helps, here is the one you can reproduce. https://github.com/bridgedxyz/services/tree/main/scene-store-service
