### ISSUE TITLE
[FEATURE] Conditional Validation

### ISSUE THREAD

**Issue by derekzernach** [dynamoose/dynamoose#1158] opened 2021-03-15 16:35 UTC
### Summary:

Would love if there was a way to run validation on an attribute if a different attribute is set to a specific value.

#### General
In a different package(`https://github.com/clarkie/dynogels`) that i'm using, it uses Joi where I can do this...

`age: Joi.when('application_id', { is: 'foo', then: Joi.string().trim().required(), })`

So this attribute is only required if `application_id` is set to `foo`. Doesn't necessarily have to use Joi, thats just what that other package uses.

[QA Discussion](https://github.com/dynamoose/dynamoose/discussions/1157)

### Other:
- [x] I have read through the Dynamoose documentation before posting this issue
- [x] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this feature has not already been suggested before
- [x] I have filled out all fields above
- [x] I am running the latest version of Dynamoose

**Comment by fishcharlie** [comment] 2021-03-15 19:16
After thinking about this a bit more. This seems like it'd be a good plugin for Dynamoose. In v3 I'm planning to explore basic plugin support.

In v3 I will either develop a plugin to support Joi validation, **or** support Joi validation natively.

Might also be interesting to explore having a validate function on the schema itself. That way you can validate the entire item and ensure the entire item is what you expect.

**Comment by vangyyy** [comment] 2021-03-22 18:44
+1 for this. I am currently using joi for validation, but it's kind of an ugly solution to have multiple validation layers. I have looked into dynogels, but it's main flaw was that it deos not support joi's 'external' validation method, which makes it impossible to validate in async manner (calling an external API for example).

**Comment by simlevesque** [comment] 2021-09-11 00:16
@fishcharlie would you be interested in using zod instead of joi ? It's api is pretty much a drop in replacement for Joi and it can be fully typed, unlike Joi which cannot ever be typed well by design.

**Comment by fishcharlie** [comment] 2021-09-11 00:34
@simlevesque I'm leaning towards the following solution:

- Implement a `validate` method on the Schema itself. (this will be a function that the item/document is passed into, or potentially an array of functions).
- Add support for plugins #851 
- dynamoose would build and maintain plugins for Joi support

As for zod support, not sure that is something Dynamoose will officially build a plugin for. But under this system, anyone could. That isn't to say Dynamoose won't build an official plugin for it, but that I'm punting on making that deceision for now.

All of this is **currently** planned for v3.

I will mention that Dynamoose by design does runtime type checking. So the need for type checking based validation as beneficial.

**Comment by fishcharlie** [comment] 2021-12-18 19:33
So based on my last comment.

> Implement a `validate` method on the Schema itself

This is done, and will be included in the next v3 release (by the end of this weekend at the latest, if a new release hasn't been released by the end of the weekend please remind me to do so).

Additionally (and kinda unrelated), there is support for `get` and `set` modifiers on the schema settings itself.

> this will be a function that the item/document is passed into, or potentially an array of functions

This is a function that the item object is passed into. It does **not** currently accept an array of functions. If someone believes having an array of functions would be valuable, please create a new feature request issue for this.

> Add support for plugins #851

Sadly, I have no idea if this is going to make it into v3. It's really hard to say at this point.

> dynamoose would build and maintain plugins for Joi support

See above. This is even less likely at this point.

---

Example:

```js
const schema = new dynamoose.Schema({
	"id": String,
	"name": String
}, {
	"validate": (obj) => {
		if (!obj.id.beginsWith(name[0])) {
			throw new Error("id first letter of name.");
		}

		return true;
	}
});
```

---

So the short version: This is now possible. But not quite as seamless as it would be if Dynamoose had a Joi plugin.

So I will be closing this issue.

---

Disclaimer: I still have not used Joi before. Would appreciate someone testing out this new functionality to see if they can get it working, and report back if it's successful or if the API needs to be changed or can be improved to better fit Joi validation.

**Closed by fishcharlie** 2021-12-18 19:33 UTC
Labels: type:enhancement

**Comment by derekzernach** [comment] 2021-12-20 14:27
@fishcharlie do you have an example of how to accomplish my initial code sample above with your validate function?

**Comment by fishcharlie** [comment] 2021-12-20 15:56
@derekzernach Disclaimer, as I said above, I haven't used Joi before. But here is my best shot at it (at the very least I'm sure that my pseudocode matches the Dynamoose code). If my pseudocode is not accurate, then you will need to make adjustments as necessary.

Pseudocode:

```
If `application_id` equals `"foo"`:
	- Trim `age`
	- Ensure `age` is not undefined or null
Else:
	- Nothing
```

Dynamoose Code:

```js
new dynamoose.Schema({
	"application_id": String,
	"age": String
}, {
	"set": (item) => {
		if (item.application_id === "foo") {
			item.age = item.age.trim();
		}

		return item;
	},
	"validate": (item) => {
		if (item.application_id === "foo") {
			if (item.age === undefined || item.age === null) {
				throw new Error("age is required");
			}
		}
	}
});
```

**Comment by derekzernach** [comment] 2021-12-20 16:38
awesome, thank you!
